# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 16:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('apelido', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
            bases=('core.usuario',),
        ),
    ]
