# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=240)),
                ('ano_ofertado', models.SmallIntegerField()),
                ('semestre_ofertado', models.CharField(max_length=1)),
                ('id_turma', models.CharField(max_length=1)),
                ('numero', models.IntegerField()),
                ('data_limite_entrega', models.DateField()),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='arquivo_questao',
            fields=[
                ('questao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.questao')),
                ('arquivo', models.FileField(upload_to='')),
            ],
            bases=('core.questao',),
        ),
    ]
