# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_arquivo_questao_questao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo_questao',
            name='arquivo',
            field=models.FileField(upload_to='arquivos/'),
        ),
    ]
