# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171126_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='disciplina_ofertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=240)),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='turma',
            fields=[
                ('disciplina_ofertada_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.disciplina_ofertada')),
                ('turno', models.CharField(max_length=15)),
                ('ra_professor', models.IntegerField()),
            ],
            bases=('core.disciplina_ofertada',),
        ),
    ]
